matrix:
  include:

    - language: c

      before_install:
        - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

      install:
        - arduino --install-library "ESP32 AnalogWrite"
        - arduino --install-library "ServoESP32"
        - arduino --install-library "Smartcar shield"
        - arduino --install-library "VL53L0X"
        
      script:
        - build_platform esp32

    - language: android
      dist: trusty

      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache

      android:
        components:
        - tools
        - platform-tools
        - tools
        - extra-android-m2repository
        - extra-google-m2repository

      before_script:
        - chmod +x $TRAVIS_BUILD_DIR/app/gradlew
        
      before_install:
        - yes | sdkmanager "platforms;android-29"
        - yes | sdkmanager "build-tools;29.0.3"

      script:
        - cd $TRAVIS_BUILD_DIR/app
        - ./gradlew build --stacktrace
        - ./gradlew test --info

notifications:
  email:
    on_success: change
    on_failure: change
