    language: c
    before_install:
      - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
    install:
      - arduino --install-library "ESP32 AnalogWrite"
      - arduino --install-library "ServoESP32"
      - arduino --install-library "Smartcar shield"
    script:
      - arduino --verify --board arduino:avr:esp32 $PWD/SmartCar/SmartCar.ino
    notifications:
      email:
        on_success: change
        on_failure: change
