    language: c
    before_install:
      - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
    install:
      - arduino --install-library "ESP32 AnalogWrite"
      - arduino --install-library "ServoESP32"
      - arduino --install-library "Smartcar shield"
      - arduino --install-library "VL53L0X"
    script:
      - build_platform esp32
    notifications:
      email:
        on_success: change
        on_failure: change
