name: Group 2 Android CI

on: [push, pull_request]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build app
        run: |
          cd app
          ./gradlew build --stacktrace

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run unit tests
        run: |
          cd app
          ./gradlew test --info

  # run-instrumented-tests:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Clone Repo
  #       uses: actions/checkout@v2
  #     - name: Run instrumented tests
  #       uses: reactivecircus/android-emulator-runner@v2
  #       with:
  #         api-level: 29
  #         script: cd android && ./gradlew connectedAndroidTest